CREATE TABLE ENDERECO (
    ID INT PRIMARY KEY,
    Rua VARCHAR(255) NOT NULL,
    Numero VARCHAR(10),
    Bairro VARCHAR(100),
    CEP VARCHAR(8),
    Cidade VARCHAR(100) NOT NULL,
    Estado CHAR(2) NOT NULL
);


CREATE TABLE USUARIO (
    CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Endereco_ID INT,
    FOREIGN KEY (Endereco_ID) REFERENCES ENDERECO(ID)
);


CREATE TABLE TELEFONES (
    CPF_USUARIO VARCHAR(11) NOT NULL,
    NUMERO VARCHAR(9) NOT NULL,
    DDD CHAR(2) NOT NULL,
    PRIMARY KEY (CPF_USUARIO, NUMERO, DDD), -- Chave Primária Composta
    FOREIGN KEY (CPF_USUARIO) REFERENCES USUARIO(CPF)
);


CREATE TABLE CORRETOR (
    CPF VARCHAR(11) PRIMARY KEY,
    CRECI VARCHAR(20) UNIQUE NOT NULL,
    DataAdmissao DATE NOT NULL,
    ComissaoPadrao NUMERIC(5, 2),
    FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);




CREATE TABLE PROPRIETARIO (
    CPF VARCHAR(11) PRIMARY KEY,
    Banco VARCHAR(50),
    Agencia VARCHAR(10),
    Conta VARCHAR(20),
    FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);




CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    CPF_Corretor VARCHAR(11),
    PreferenciasImovel TEXT,
    FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
    FOREIGN KEY (CPF_Corretor) REFERENCES CORRETOR(CPF)
);


CREATE TABLE IMOVEL (
    ID_Imovel INT PRIMARY KEY,
    CPF_Proprietario VARCHAR(11) NOT NULL,
    CPF_Corretor VARCHAR(11),
    Tipo VARCHAR(50) NOT NULL,
    Endereco_ID INT NOT NULL,
    AreaTotal NUMERIC(10, 2),
    ValorVendaLocacao NUMERIC(15, 2),
    Status VARCHAR(20) NOT NULL,
    Descricao TEXT,
    FOREIGN KEY (CPF_Proprietario) REFERENCES PROPRIETARIO(CPF),
    FOREIGN KEY (CPF_Corretor) REFERENCES CORRETOR(CPF),
    FOREIGN KEY (Endereco_ID) REFERENCES ENDERECO(ID)
);




CREATE TABLE PROPOSTA (
    ID_Proposta INT PRIMARY KEY,
    ID_Imovel INT NOT NULL,
    CPF_Cliente VARCHAR(11) NOT NULL,
    ValorProposto NUMERIC(15, 2) NOT NULL,
    DataHoraProposta TIMESTAMP NOT NULL,
    Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_Imovel) REFERENCES IMOVEL(ID_Imovel),
    FOREIGN KEY (CPF_Cliente) REFERENCES CLIENTE(CPF)
);




CREATE TABLE CONTRATO (
    ID_Contrato INT PRIMARY KEY,
    ID_Proposta INT UNIQUE NOT NULL,
    Tipo VARCHAR(50) NOT NULL,
    DataInicio DATE NOT NULL,
    DataTermino DATE,
    ValorFinal NUMERIC(15, 2) NOT NULL,
    FOREIGN KEY (ID_Proposta) REFERENCES PROPOSTA(ID_Proposta)
);


CREATE TABLE AGENDA (
    ID_Imovel INT NOT NULL,
    CPF_Cliente VARCHAR(11) NOT NULL,
    CPF_Corretor VARCHAR(11) NOT NULL,
    DataHoraVisita TIMESTAMP NOT NULL,
    StatusVisita VARCHAR(20),
    PRIMARY KEY (ID_Imovel, CPF_Cliente, DataHoraVisita),
    FOREIGN KEY (ID_Imovel) REFERENCES IMOVEL(ID_Imovel),
    FOREIGN KEY (CPF_Cliente) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (CPF_Corretor) REFERENCES CORRETOR(CPF)
);


CREATE TABLE INTERMEDIA (
    ID_Imovel INT NOT NULL,
    CPF_Proprietario VARCHAR(11) NOT NULL,
    CPF_Corretor VARCHAR(11) NOT NULL,
    Tipo VARCHAR(50),
    PRIMARY KEY (ID_Imovel, CPF_Corretor),
    FOREIGN KEY (ID_Imovel) REFERENCES IMOVEL(ID_Imovel),
    FOREIGN KEY (CPF_Proprietario) REFERENCES PROPRIETARIO(CPF),
    FOREIGN KEY (CPF_Corretor) REFERENCES CORRETOR(CPF)
);


CREATE TABLE GERENCIA (
    CPF_Cliente VARCHAR(11) NOT NULL,
    CPF_Corretor_Principal VARCHAR(11) NOT NULL,
    PRIMARY KEY (CPF_Cliente, CPF_Corretor_Principal),
    FOREIGN KEY (CPF_Cliente) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (CPF_Corretor_Principal) REFERENCES CORRETOR(CPF)
);
